// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.14.0

package db

import (
	"context"

	"github.com/google/uuid"
)

type Querier interface {
	CreateFeatureFlag(ctx context.Context, arg CreateFeatureFlagParams) (FeatureFlag, error)
	DeleteFeatureFlag(ctx context.Context, featureID uuid.UUID) error
	GetAllFeatureFlags(ctx context.Context) ([]FeatureFlag, error)
	GetFeatureFlagByFeatureLayer(ctx context.Context, featureLayer FeatureLayer) ([]FeatureFlag, error)
}

var _ Querier = (*Queries)(nil)
